# Generated by Django 2.2.4 on 2020-03-09 05:44

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('incomplete_mean', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='birthdate',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='¿Cuál es su fecha de nacimiento? Por favor, use el formato día-mes-año (por ejemplo, 30-01-1998).'),
        ),
    ]
