# Generated by Django 2.2.4 on 2020-03-09 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomplete_mean', '0003_auto_20200309_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='birthdate',
        ),
    ]
