# Generated by Django 2.2.4 on 2020-03-06 05:19

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('complete_random', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='decision',
            field=otree.db.models.StringField(choices=[('B', 'B'), ('A', 'A')], max_length=10000, null=True),
        ),
    ]
