# Generated by Django 2.2.4 on 2020-03-06 18:37

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('complete_mean', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='dummy_decision',
            field=otree.db.models.StringField(choices=[('A', 'A'), ('B', 'B')], max_length=10000, null=True),
        ),
    ]
