# Generated by Django 2.2.4 on 2020-03-06 18:41

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('complete_mean', '0002_player_dummy_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='dummy_decision',
            field=otree.db.models.StringField(choices=[('B', 'B'), ('A', 'A')], max_length=10000, null=True),
        ),
    ]
