# Generated by Django 2.2.4 on 2020-03-09 05:12

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey2_group', to='otree.Session')),
            ],
            options={
                'db_table': 'survey2_group',
            },
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey2_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'survey2_subsession',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('birthdate', otree.db.models.StringField(max_length=10000, null=True, verbose_name='¿Cuál es su fecha de nacimiento? Por favor, use el formato día-mes-año (por ejemplo, 30-01-1998).')),
                ('gender', otree.db.models.StringField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10000, null=True, verbose_name='¿Cuál es su género?')),
                ('maternal_lang', otree.db.models.StringField(max_length=10000, null=True, verbose_name='¿Cuál es su idioma materno?')),
                ('dialect', otree.db.models.StringField(max_length=10000, null=True, verbose_name='¿Se identifica usted como hablante de un dialecto particular o variedad de este idioma (o idiomas)? ¿En caso afirmativo, cómo se llama ese dialecto o en dónde se habla?')),
                ('other_langs', otree.db.models.StringField(max_length=10000, null=True, verbose_name='¿Qué otros idiomas habla bien?')),
                ('langs_used_weekly', otree.db.models.StringField(max_length=10000, null=True, verbose_name='¿Qué idiomas (incluyendo sus idiomas maternos y el Castellano) usa al menos una vez a la semana?')),
                ('nationality', otree.db.models.StringField(max_length=10000, null=True, verbose_name='¿Cuál es su nacionalidad?')),
                ('birthplace', otree.db.models.StringField(max_length=10000, null=True, verbose_name='¿Donde nació usted? (Ciudad, Provincia/Estado, País)')),
                ('residence', otree.db.models.StringField(max_length=10000, null=True, verbose_name='¿En qué país reside?')),
                ('bool_country', otree.db.models.StringField(choices=[('Sí', 'Sí'), ('No', 'No')], max_length=10000, null=True, verbose_name='¿Ha vivido toda su vida en el país en el que nació?')),
                ('other_countries', otree.db.models.StringField(max_length=10000, null=True, verbose_name="Si ha vivido en otros países además de aquel en que nació, por favor indique en cuáles señalando cuántos años vivió en cada uno. Use el siguiente formato: EEUU, 4, Francia, 2, Chile, 1, etc. Si no ha vivido en otros paises, escribe 'NA'.")),
                ('bool_student', otree.db.models.StringField(choices=[('Sí', 'Sí'), ('No', 'No')], max_length=10000, null=True, verbose_name='¿Es usted estudiante?')),
                ('profession', otree.db.models.StringField(max_length=10000, null=True, verbose_name="Si usted no es estudiante, ¿cuál es su profesión? Si es estudiante, escriba 'NA' en la caja")),
                ('education_level', otree.db.models.StringField(choices=[('Ninguno', 'Ninguno'), ('Educación Inicial (Jardín)', 'Educación Inicial (Jardín)'), ('Educación General Básica (Primaria)', 'Educación General Básica (Primaria)'), ('Bachillerato (Secundaria)', 'Bachillerato (Secundaria)'), ('Algo de estudios universitarios (actualmente o pasado)', 'Algo de estudios universitarios (actualmente o pasado)'), ('Instituto Técnico', 'Instituto Técnico'), ('Licenciatura o equivalente', 'Licenciatura o equivalente'), ('Maestría o equivalente', 'Maestría o equivalente'), ('Doctorado', 'Doctorado')], max_length=10000, null=True, verbose_name='¿Cuál es su nivel educativo?')),
                ('edu_countries', otree.db.models.StringField(max_length=10000, null=True, verbose_name='¿En que países recibió su educación?')),
                ('edu_langs', otree.db.models.StringField(max_length=10000, null=True, verbose_name='¿En que idiomas recibió su educación? Por favor especifique.')),
                ('phil_course_count', otree.db.models.StringField(choices=[('Nunca he tomado un curso de Filosofía', 'Nunca he tomado un curso de Filosofía'), ('He tomado 1 o 2 cursos de Filosofía', 'He tomado 1 o 2 cursos de Filosofía'), ('He tomado más de 2 cursos de Filosofía, pero la Filosofía no es la disciplina en la que fui formado.', 'He tomado más de 2 cursos de Filosofía, pero la Filosofía no es la disciplina en la que fui formado.'), ('Estudio Filosofía y estoy por obtener una licenciatura en Filosofía.', 'Estudio Filosofía y estoy por obtener una licenciatura en Filosofía.'), ('Estudio Filosofía y tengo una licenciatura en Filosofía.', 'Estudio Filosofía y tengo una licenciatura en Filosofía.'), ('Estoy estudiando un posgrado en Filosofía.', 'Estoy estudiando un posgrado en Filosofía.'), ('Tengo un doctorado en Filosofía', 'Tengo un doctorado en Filosofía')], max_length=10000, null=True, verbose_name='¿Cuántos cursos de Filosofía recibió durante sus estudios?')),
                ('parents_edu_level', otree.db.models.StringField(choices=[('Ninguno', 'Ninguno'), ('Educación Inicial (Jardín)', 'Educación Inicial (Jardín)'), ('Educación General Básica (Primaria)', 'Educación General Básica (Primaria)'), ('Bachillerato (Secundaria)', 'Bachillerato (Secundaria)'), ('Algunos estudios universitarios', 'Algunos estudios universitarios'), ('Instituto Técnico', 'Instituto Técnico'), ('Licenciatura o equivalente', 'Licenciatura o equivalente'), ('Maestría o equivalente', 'Maestría o equivalente'), ('Doctorado', 'Doctorado')], max_length=10000, null=True, verbose_name='Hasta donde sabe, ¿cuál es el nivel educativo más alto que alcanzó alguno de sus padres (el que tenga más estudios)?')),
                ('religion', otree.db.models.StringField(choices=[('Ninguna', 'Ninguna'), ('Católica', 'Católica'), ('Evangelista', 'Evangelista'), ('Protestante (distinto de evangelista)', 'Protestante (distinto de evangelista)'), ('Mormona', 'Mormona'), ('Cristiana ortodoxa', 'Cristiana ortodoxa'), ('Cristiana (otra)', 'Cristiana (otra)'), ('Judía', 'Judía'), ('Musulmana', 'Musulmana'), ('Hinduísta', 'Hinduísta'), ('Budista', 'Budista'), ('Sintoísta', 'Sintoísta'), ('Confucionista', 'Confucionista'), ('Daoista', 'Daoista'), ('Jainista', 'Jainista'), ('Sikh', 'Sikh'), ('Atea o agnóstica', 'Atea o agnóstica'), ('Otra', 'Otra')], max_length=10000, null=True, verbose_name='¿Cuál es su afiliación religiosa actual? Por favor marque todas las opciones aplicables.\t')),
                ('rel_freq', otree.db.models.StringField(choices=[('Diariamente', 'Diariamente'), ('Semanalmente', 'Semanalmente'), ('Mensualmente', 'Mensualmente'), ('Unas cuantas veces al año', 'Unas cuantas veces al año'), ('Nunca', 'Nunca')], max_length=10000, null=True, verbose_name='¿Con qué frecuencia participa en actividades religiosas?')),
                ('rel_import', otree.db.models.StringField(choices=[('No es importante en absoluto', 'No es importante en absoluto'), ('Un poco importante', 'Un poco importante'), ('Algo importante', 'Algo importante'), ('Importante', 'Importante'), ('Muy importante', 'Muy importante')], max_length=10000, null=True, verbose_name='¿Qué tan importante es la religión en su vida?')),
                ('politics', otree.db.models.StringField(choices=[('Muy de izquierda', 'Muy de izquierda'), ('Izquierda', 'Izquierda'), ('Centro-izquierda', 'Centro-izquierda'), ('Centro', 'Centro'), ('Centro-derecha', 'Centro-derecha'), ('Derecha', 'Derecha'), ('Muy de derecha', 'Muy de derecha')], max_length=10000, null=True, verbose_name='En términos generales, ¿cuál es su inclinación política?')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey2.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey2_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey2_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey2.Subsession')),
            ],
            options={
                'db_table': 'survey2_player',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey2.Subsession'),
        ),
    ]
