# Generated by Django 2.2.4 on 2020-03-10 15:29

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey2', '0002_auto_20200310_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='other_langs',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='¿Qué idiomas habla bien?'),
        ),
    ]
