# Generated by Django 2.2.4 on 2020-03-10 16:09

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey2', '0004_player_civil_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ethnicity',
            field=otree.db.models.StringField(choices=[('Afro-Ecuatoriana', 'Afro-Ecuatoriana'), ('Mestiza', 'Mestiza'), ('Asiatica', 'Asiatica'), ('Indígena', 'Indígena'), ('Blanca', 'Blanca'), ('Prefiero no decir', 'Prefiero no decir')], max_length=10000, null=True, verbose_name='¿Con que etnia se identifica?'),
        ),
    ]
