# Generated by Django 2.2.4 on 2020-03-05 19:14

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('expgame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsession',
            name='average',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
