# Generated by Django 2.2.4 on 2020-03-05 19:17

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('expgame', '0002_subsession_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsession',
            name='average',
            field=otree.db.models.CurrencyField(default=0, null=True),
        ),
    ]
