# Generated by Django 2.2.4 on 2020-03-10 15:26

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='identity',
            field=otree.db.models.StringField(choices=[('Sí', 'Sí'), ('No', 'No'), ('Quizás', 'Quizás')], max_length=10000, null=True, verbose_name='Si conocieras de antemano a los otros participantes, ¿habrías tomado una decisión diferente?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='intent',
            field=otree.db.models.StringField(choices=[('Interesados', 'Interesados'), ('Generosos', 'Generosos'), ('Hostiles', 'Hostiles'), ('Cooperativos', 'Cooperativos'), ('Racionales', 'Racionales'), ('Irracionales', 'Irracionales')], max_length=10000, null=True, verbose_name='¿Cómo calificarías las intenciones de los otros participantes en la sesión?'),
        ),
    ]
